export default Object.freeze(
  [
    "",
    "Health",
    "Recovery Speed",
    "Recovery",
    "Vampirism",
    "Herbal Science",
    "Stamina Recovery",
    "Hunger",
    "Stamina",
    "Eating",
    "Gluttony",
    "Strong Attack",
    "Attack",
    "Lone Wolf",
    "Issen",
    "Expert",
    "Flash Conversion",
    "Exploit Weakness",
    "Stylish Assault",
    "Dissolver",
    "Status Assault",
    "Drug Knowledge",
    "Status",
    "Abnormality",
    "Fire Attack",
    "Water Attack",
    "Thunder Attack",
    "Ice Attack",
    "Dragon Attack",
    "Elemental Attack",
    "Bomb Boost",
    "Gunnery",
    "Encourage",
    "Flute Expert",
    "Martial Arts",
    "Survivor",
    "Rage",
    "Adrenaline",
    "Skilled",
    "Trained",
    "Fasting",
    "Focus",
    "Charge Attack Up",
    "Weapon Handling",
    "Shiriagari",
    "Adaptation",
    "Combat Supremacy",
    "Vigorous",
    "Thunder Clad",
    "Lavish Attack",
    "Obscurity",
    "Rush",
    "Ceaseless",
    "Point Breakthrough",
    "Furious",
    "Determination",
    "Vitality",
    "Reflect",
    "Defense",
    "Fortication",
    "Guard",
    "Auto-Guard",
    "Breakout",
    "Sharpening",
    "Sharpness",
    "Stylish",
    "Edgemaster",
    "Artisan",
    "Bomb Sword",
    "Poison Sword",
    "Paralysis Sword",
    "Sleep Sword",
    "Fire Sword",
    "Water Sword",
    "Dragon Sword",
    "Thunder Sword",
    "Ice Sword",
    "Fencing",
    "Sword God",
    "Steady Hand",
    "Normal Shot Up",
    "Pierce Shot Up",
    "Pellet Shot Up",
    "Normal Shot Add",
    "Pierce Shot Add",
    "Pellet Shot Add",
    "Crag Shot Add",
    "Cluster Shot Add",
    "Poison Coating Add",
    "Paralysis Coating Add",
    "Sleep Coating Add",
    "Mounting",
    "Gentle Shot",
    "Loading",
    "Rapid Fire",
    "Auto-Reload",
    "Reload",
    "Recoil",
    "Critical Shot",
    "Precision",
    "Ammo Combiner",
    "Bullet Saver",
    "Sniper",
    "Spacing",
    "SnS Tech",
    "DS Tech",
    "LS Tech",
    "GS Tech",
    "Hammer Tech",
    "HH Tech",
    "Lance Tech",
    "GL Tech",
    "SAF Tech",
    "Tonfa Tech",
    "MS Tech",
    "HBG Tech",
    "LBG Tech",
    "Bow Tech",
    "All Res Up",
    "Fire Res",
    "Water Res",
    "Thunder Res",
    "Ice Res",
    "Dragon Res",
    "Poison Res",
    "Paralysis Res",
    "Sleep Res",
    "Status Res",
    "Stun Res",
    "Deoderant",
    "Snowball Res",
    "Vocal Chords",
    "Def Lock",
    "Drunk",
    "Blast Res",
    "Magnet Res",
    "Crystal Res",
    "Freeze Res",
    "Three Worlds Protection",
    "Hearing Protection",
    "Quake Res",
    "Wind Pressure",
    "Anti-Theft",
    "Heat Res",
    "Cold Res",
    "Light Tread",
    "Terrain",
    "Evasion Boost",
    "Evasion",
    "Evade Extender",
    "Passive",
    "Protection",
    "Guts",
    "Absolute Defense",
    "Combo Expert",
    "Everlasting",
    "Wide-Area",
    "Whim",
    "Throwing",
    "Strong Arm",
    "Ranger",
    "Cooking",
    "Fishing",
    "Combining",
    "Alchemy",
    "Speed Setup",
    "Íron Arm",
    "Knife Throwing",
    "Map",
    "Psychic",
    "Stealth",
    "Incitement",
    "Backpacking",
    "Speed Gather",
    "Gathering",
    "Carving",
    "Mindfulness",
    "Fate",
    "Pressure",
    "Monster",
    "Breeder",
    "Bond",
    "Inspiration",
    "Capture Proficiency",
    "Relief",
    "Caring",
    "Movement Speed",
    "Reinforcement",
    "Assistance",
    "Grace",
    "Compensation",
    "Dark Pulse",
    "Blazing Grace",
    "Drawing Arts",
    "Ice Age",
  ].reduce((acc, skill, index) => {
    acc[index] = skill;
    return acc;
  }, {})
);
