// Copyright 2023 Doriel Rivalet
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.

export default Object.freeze({
  0: "None",
  1: "Attack Slayer",
  2: "Elemental Slayer",
  3: "Status Attack Slayer",
  4: "Affinity Slayer",
  5: "Defense Slayer",
  6: "Stun Value Slayer",
  7: "Flying Wyvern Slayer",
  8: "Bird Wyvern Slayer",
  9: "Carapaceon Slayer",
  10: "Piscine Slayer",
  11: "Fanged Beast Slayer",
  12: "Brute Wyvern Slayer",
  13: "Leviathan Slayer",
  14: "Elder Dragon Slayer",
  15: "Small Monster Slayer",
  16: "Elemental Coating/Crystal",
  17: "Hot",
  18: "Cold",
  19: "Morning",
  20: "Night",
  21: "Breeding Season",
  22: "Warm Season",
  23: "Cold Season",
  24: "Monday",
  25: "Tuesday",
  26: "Wednesday",
  27: "Thursday",
  28: "Friday",
  29: "Saturday",
  30: "Sunday",
  31: "Manager",
  32: "Balloon",
  33: "Dowsing",
  34: "Hunter Soul",
  35: "Soul Collection",
  36: "Gook's Friend",
  37: "Halk's Friend",
  38: "Money Expert",
  39: "Exp Expert",
  40: "Omnivore",
  41: "Carving Division",
  42: "Sleeping",
  43: "Decoy",
  44: "Spoilt",
  45: "Unity",
  46: "Aid",
  47: "Rapid Fire Add",
  48: "Ultra Rapid Fire Add",
  49: "Disable Rapid",
  50: "Heat Cannon Add",
  51: "Ballista Saver",
  52: "Raw Bow Boost",
  53: "Raw SnS Boost",
  54: "Sonic Bomb Range",
  55: "T.Boost(SnS)",
  56: "T.Boost(DS)",
  57: "T.Boost(GS)",
  58: "T.Boost(LS)",
  59: "T.Boost(Lance)",
  60: "T.Boost(GL)",
  61: "T.Boost(Hammer)",
  62: "T.Boost(HH)",
  63: "T.Change(SnS)",
  64: "T.Change(DS)",
  65: "T.Change(GS)",
  66: "T.Change(LS)",
  67: "T.Change(Lance)",
  68: "T.Change(GL)",
  69: "T.Change(Ham)",
  70: "T.Change(HH)",
  71: "T.Change(LBG)",
  72: "T.Change(HBG)",
  73: "T.Change(Bow)",
  74: "Length Up",
  75: "Shelling Change",
  76: "Note Change 1",
  77: "Note Change 2",
  78: "Note Change 3",
  79: "Arc Shot Change",
  80: "Rarity Change",
  81: "Shelling Boost",
  82: "Tech Boost Bow",
  83: "Cat Breeder",
  84: "Shot Change",
  85: "Draw Strength(GS)",
  86: "Draw Strength(Hammer)",
  87: "Draw Strength(Lance)",
  88: "Draw Strength(SnS)",
  89: "Draw Strength(DS)",
  90: "Draw Strength(LS)",
  91: "Draw Strength(HH)",
  92: "Draw Strength(GL)",
  93: "Draw Strength(Tonfa)",
  94: "Tech Boost Tonfa",
  95: "Fanged Wyvern Slayer",
  96: "Unsheathed Movement Speed",
  97: "Tech Boost Swaxe",
  98: "Tech Boost HBG",
  99: "Great Sword Up",
  100: "Heavy Bowgun Up",
  101: "Hammer Up",
  102: "Lance Up",
  103: "Sword and Shield Up",
  104: "Light Bowgun Up",
  105: "Dual Swords Up",
  106: "Long Sword Up",
  107: "Hunting Horn Up",
  108: "Gunlance Up",
  109: "Bow Up",
  110: "Tonfa Up",
  111: "Swaxe Up",
  112: "Magspike Up",
  113: "Zenith Cooldown",
  114: "Zenith Duration",
  115: "Zenith Fire Res",
  116: "Zenith Water Res",
  117: "Zenith Ice Res",
  118: "Zenith Thunder Res",
  119: "Zenith Dragon Res",
  120: "Zenith Healing",
  121: "Zenith Heroics",
  122: "Zenith Attack",
  123: "Zenith Elemental",
  124: "Zenith Movement Speed",
  125: "All Zenith AOEs",
});
