// Copyright 2023 Doriel Rivalet
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.

namespace EZlion.Mapper;

///<summary>
///The armor colors list
///</summary>
public static class ArmorColor
{
    /// <summary>
    /// Gets the name of the armor color identifier.
    /// </summary>
    /// <value>
    /// The name of the armor color identifier.
    /// </value>
    public static ReadOnlyDictionary<int, string> IDName { get; } = new(new Dictionary<int, string>
    {
        { 0, "Material Green 0" },
        { 1, "Powerful Red 0" },
        { 2, "Seized White 0" },
        { 3, "Festival Pink 0" },
        { 4, "Friendly Blue 0" },
        { 5, "Rare Navy 0" },
        { 6, "Armored Cyan 0" },
        { 7, "Combat Purple 0" },
        { 8, "Guided Orange 0" },
        { 9, "Gigantic Yellow 0" },
        { 10, "Dining Grey 0" },
        { 11, "Changing Rainbow" },
        { 12, "Material Green 1" },
        { 13, "Material Green 2" },
        { 14, "Material Green 3" },
        { 15, "Material Green 4" },
        { 16, string.Empty },
        { 17, string.Empty },
        { 18, string.Empty },
        { 19, string.Empty },
        { 20, string.Empty },
        { 21, "Powerful Red 1" },
        { 22, "Powerful Red 2" },
        { 23, "Powerful Red 3" },
        { 24, "Powerful Red 4" },
        { 25, string.Empty },
        { 26, string.Empty },
        { 27, string.Empty },
        { 28, string.Empty },
        { 29, string.Empty },
        { 30, string.Empty },
        { 31, string.Empty },
        { 32, string.Empty },
        { 33, string.Empty },
        { 34, string.Empty },
        { 35, string.Empty },
        { 36, string.Empty },
        { 37, string.Empty },
        { 38, string.Empty },
        { 39, "Festival Pink 1" },
        { 40, "Festival Pink 2" },
        { 41, "Festival Pink 3" },
        { 42, "Festival Pink 4" },
        { 43, string.Empty },
        { 44, string.Empty },
        { 45, string.Empty },
        { 46, string.Empty },
        { 47, string.Empty },
        { 48, "Friendly Blue 1" },
        { 49, "Friendly Blue 2" },
        { 50, "Friendly Blue 3" },
        { 51, "Friendly Blue 4" },
        { 52, string.Empty },
        { 53, string.Empty },
        { 54, string.Empty },
        { 55, string.Empty },
        { 56, string.Empty },
        { 57, "Rare Navy 1" },
        { 58, "Rare Navy 2" },
        { 59, "Rare Navy 3" },
        { 60, "Rare Navy 4" },
        { 61, string.Empty },
        { 62, string.Empty },
        { 63, string.Empty },
        { 64, string.Empty },
        { 65, string.Empty },
        { 66, "Armored Cyan 1" },
        { 67, "Armored Cyan 2" },
        { 68, "Armored Cyan 3" },
        { 69, "Armored Cyan 4" },
        { 70, string.Empty },
        { 71, string.Empty },
        { 72, string.Empty },
        { 73, string.Empty },
        { 74, string.Empty },
        { 75, "Combat Purple 1" },
        { 76, "Combat Purple 2" },
        { 77, "Combat Purple 3" },
        { 78, "Combat Purple 4" },
        { 79, string.Empty },
        { 80, string.Empty },
        { 81, string.Empty },
        { 82, string.Empty },
        { 83, string.Empty },
        { 84, "Guided Orange 1" },
        { 85, "Guided Orange 2" },
        { 86, "Guided Orange 3" },
        { 87, "Guided Orange 4" },
        { 88, string.Empty },
        { 89, string.Empty },
        { 90, string.Empty },
        { 91, string.Empty },
        { 92, string.Empty },
        { 93, "Gigantic Yellow 1" },
        { 94, "Gigantic Yellow 2" },
        { 95, "Gigantic Yellow 3" },
        { 96, "Gigantic Yellow 4" },
        { 97, string.Empty },
        { 98, string.Empty },
        { 99, string.Empty },
        { 100, string.Empty },
        { 101, string.Empty },
        { 102, "Dining Grey 1" },
        { 103, "Dining Grey 2" },
        { 104, "Dining Grey 3" },
        { 105, "Dining Grey 4" },
    });
};
