using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EZlion.Mapper
{
    ///<summary>
    ///The armor colors list
    ///</summary>
    public static class ArmorColor
    {
        /// <summary>
        /// Gets the name of the armor color identifier.
        /// </summary>
        /// <value>
        /// The name of the armor color identifier.
        /// </value>
        public static IReadOnlyDictionary<int, string> IDName { get; } = new Dictionary<int, string>
        {
            { 0, "Material Green 0"},
            { 1, "Powerful Red 0"},
            { 2, "Seized White 0"},
            { 3, "Festival Pink 0"},
            { 4, "Friendly Blue 0"},
            { 5, "Rare Navy 0"},
            { 6, "Armored Cyan 0"},
            { 7, "Combat Purple 0"},
            { 8, "Guided Orange 0"},
            { 9, "Gigantic Yellow 0"},
            { 10, "Dining Grey 0"},
            { 11, "Changing Rainbow"},
            { 12, "Material Green 1"},
            { 13, "Material Green 2"},
            { 14, "Material Green 3"},
            { 15, "Material Green 4"},
            { 16, ""},
            { 17, ""},
            { 18, ""},
            { 19, ""},
            { 20, ""},
            { 21, "Powerful Red 1"},
            { 22, "Powerful Red 2"},
            { 23, "Powerful Red 3"},
            { 24, "Powerful Red 4"},
            { 25, ""},
            { 26, ""},
            { 27, ""},
            { 28, ""},
            { 29, ""},
            { 30, ""},
            { 31, ""},
            { 32, ""},
            { 33, ""},
            { 34, ""},
            { 35, ""},
            { 36, ""},
            { 37, ""},
            { 38, ""},
            { 39, "Festival Pink 1"},
            { 40, "Festival Pink 2"},
            { 41, "Festival Pink 3"},
            { 42, "Festival Pink 4"},
            { 43, ""},
            { 44, ""},
            { 45, ""},
            { 46, ""},
            { 47, ""},
            { 48, "Friendly Blue 1"},
            { 49, "Friendly Blue 2"},
            { 50, "Friendly Blue 3"},
            { 51, "Friendly Blue 4"},
            { 52, ""},
            { 53, ""},
            { 54, ""},
            { 55, ""},
            { 56, ""},
            { 57, "Rare Navy 1"},
            { 58, "Rare Navy 2"},
            { 59, "Rare Navy 3"},
            { 60, "Rare Navy 4"},
            { 61, ""},
            { 62, ""},
            { 63, ""},
            { 64, ""},
            { 65, ""},
            { 66, "Armored Cyan 1"},
            { 67, "Armored Cyan 2"},
            { 68, "Armored Cyan 3"},
            { 69, "Armored Cyan 4"},
            { 70, ""},
            { 71, ""},
            { 72, ""},
            { 73, ""},
            { 74, ""},
            { 75, "Combat Purple 1"},
            { 76, "Combat Purple 2"},
            { 77, "Combat Purple 3"},
            { 78, "Combat Purple 4"},
            { 79, ""},
            { 80, ""},
            { 81, ""},
            { 82, ""},
            { 83, ""},
            { 84, "Guided Orange 1"},
            { 85, "Guided Orange 2"},
            { 86, "Guided Orange 3"},
            { 87, "Guided Orange 4"},
            { 88, ""},
            { 89, ""},
            { 90, ""},
            { 91, ""},
            { 92, ""},
            { 93, "Gigantic Yellow 1"},
            { 94, "Gigantic Yellow 2"},
            { 95, "Gigantic Yellow 3"},
            { 96, "Gigantic Yellow 4"},
            { 97, ""},
            { 98, ""},
            { 99, ""},
            { 100, ""},
            { 101, ""},
            { 102, "Dining Grey 1"},
            { 103, "Dining Grey 2"},
            { 104, "Dining Grey 3"},
            { 105, "Dining Grey 4"}
        };
    };
}
