// Copyright 2023 Doriel Rivalet
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.

namespace EZlion.Mapper;

///<summary>
/// Location names
///</summary>
public static class Location
{
    /// <summary>
    /// Gets the name of the identifier.
    /// </summary>
    /// <value>
    /// The name of the identifier.
    /// </value>
    public static ReadOnlyDictionary<int, string> IDName { get; } = new(new Dictionary<int, string>
    {
        { 0, "Loading" },
        { 1, "Jungle - Base Camp - Night" },
        { 2, "Jungle - Area 1 - Night" },
        { 3, "Jungle - Area 2 - Night" },
        { 4, "Jungle - Area 3 - Night" },
        { 5, "Jungle - Area 4 - Night" },
        { 6, "Snowy Mountains - Secret Area - Day" },
        { 7, "Desert - Secret Area - Day" },
        { 8, "Volcano - Secret Area - Day" },
        { 9, "Swamp - Secret Area - Day" },
        { 10, "Siege Fortress - Base Camp - Day" },
        { 11, "Siege Fortress - Area 4 - Day" },
        { 12, "Siege Fortress - Area 5 - Day" },
        { 13, "Arena with Moat - Area 1 - Day" },
        { 14, "Siege Fortress - Area 1 - Day" },
        { 15, "Snowy Mountains - Secret Area - Night" },
        { 16, "Swamp - Base Camp - Night" },
        { 17, "Arena with Moat - Area 1 - Night" },
        { 18, "Jungle - Area 5 - Night" },
        { 19, "Jungle - Area 9 - Night" },
        { 20, "Castle Schrade - Base Camp/Area 1" },
        { 21, "Forest and Hills - Base Camp - Day" },
        { 22, "Jungle - Area 8 - Night" },
        { 23, "Jungle - Area 7 - Night" },
        { 24, "Desert - Secret Area - Night" },
        { 25, "Castle Schrade - Area 2" },
        { 26, "Jungle - Area 6 - Night" },
        { 27, "Volcano - Secret Area - Night" },
        { 28, "Siege Fortress - Area 3 - Day" },
        { 29, "Swamp - Secret Area - Night" },
        { 30, "Siege Fortress - Area 2 - Day" },
        { 31, "Siege Fortress - Area 6 - Day" },
        { 32, "Forest and Hills - Area 6 - Day" },
        { 33, "Forest and Hills - Area 3 - Day" },
        { 34, "Forest and Hills - Area 10 - Day" },
        { 35, "Forest and Hills - Area 8 - Day" },
        { 36, "Forest and Hills - Area 9 - Day" },
        { 37, "Forest and Hills - Area 4 - Day" },
        { 38, "Forest and Hills - Area 2 - Day" },
        { 39, "Forest and Hills - Area 1 - Day" },
        { 40, "Forest and Hills - Area 5 - Day" },
        { 41, "Forest and Hills - Area 7 - Day" },
        { 42, "Forest and Hills - Area 11 - Day" },
        { 43, "Forest and Hills - Area 12 - Day" },
        { 44, "Duplicate of Swamp Night Area 1" },
        { 45, "Desert - Base Camp - Night" },
        { 46, "Arena with Moat - Base Camp - Night" },
        { 47, "Desert - Area 2 - Night" },
        { 48, "Desert - Area 7 - Night" },
        { 49, "Desert - Area 3 - Night" },
        { 50, "Desert - Area 6 - Night" },
        { 51, "Desert - Area 5 - Night" },
        { 52, "Desert - Area 1 - Night" },
        { 53, "Desert - Area 4 - Night" },
        { 54, "Desert - Area 8 - Night" },
        { 55, "Desert - Area 9 - Night" },
        { 56, "Desert - Area 10 - Night" },
        { 57, "Arena with Pillar - Area 1 - Night" },
        { 58, "Volcano - Base Camp - Night" },
        { 59, "Volcano - Area 4 - Night" },
        { 60, "Volcano - Area 5 - Night" },
        { 61, "Volcano - Area 1 - Night" },
        { 62, "Volcano - Area 2 - Night" },
        { 63, "Volcano - Area 3 - Night" },
        { 64, "Volcano - Area 7 - Night" },
        { 65, "Volcano - Area 6 - Night" },
        { 66, "Arena with Pillar (Cat Arena) - Area 1 - Night" },
        { 67, "Swamp - Area 2 - Night" },
        { 68, "Swamp - Area 3 - Night" },
        { 69, "Swamp - Area 9 - Night" },
        { 70, "Swamp - Area 8 - Night" },
        { 71, "Swamp - Area 6 - Night" },
        { 72, "Swamp - Area 5 - Night" },
        { 73, "Swamp - Area 7 - Night" },
        { 74, "Volcano - Secret Area - Night" },
        { 75, "Swamp - Area 4 - Night" },
        { 76, string.Empty },
        { 77, string.Empty },
        { 78, string.Empty },
        { 79, string.Empty },
        { 80, string.Empty },
        { 81, string.Empty },
        { 82, string.Empty },
        { 83, "Tower 3 - Area 8" },
        { 84, "Tower 3 - Area 9" },
        { 85, "Absent" },
        { 86, "Absent" },
        { 87, "Kokoto Village" },
        { 88, "Crimson Battleground" },
        { 89, "Arena with Pillar (Cat Arena) - Base Camp - Day" },
        { 90, "Arena with Ledge - Day" },
        { 91, "Arena with Pillar (Cat Arena) - Area 1 - Day" },
        { 92, "Snowy Mountains - Area 4 - Day" },
        { 93, "Snowy Mountains - Area 5 - Day" },
        { 94, "Snowy Mountains - Area 3 - Day" },
        { 95, "Snowy Mountains - Area 2 - Day" },
        { 96, "Snowy Mountains - Area 7 - Day" },
        { 97, "Snowy Mountains - Area 8 - Day" },
        { 98, "Snowy Mountains - Base Camp - Day" },
        { 99, "Snowy Mountains - Area 1 - Day" },
        { 100, "Snowy Mountains - Area 6 - Day" },
        { 101, "Snowy Mountains - Area 4 - Night" },
        { 102, "Snowy Mountains - Area 5 - Night" },
        { 103, "Snowy Mountains - Area 3 - Night" },
        { 104, "Snowy Mountains - Area 2 - Night" },
        { 105, "Snowy Mountains - Area 7 - Night" },
        { 106, "Snowy Mountains - Area 8 - Night" },
        { 107, "Snowy Mountains - Base Camp - Night" },
        { 108, "Snowy Mountains - Area 1 - Night" },
        { 109, "Snowy Mountains - Area 6 - Night" },
        { 110, "Jungle - Base Camp - Day" },
        { 111, "Jungle - Area 1 - Day" },
        { 112, "Jungle - Area 2 - Day" },
        { 113, "Jungle - Area 3 - Day" },
        { 114, "Jungle - Area 4 - Day" },
        { 115, "Jungle - Area 5 - Day" },
        { 116, "Jungle - Area 9 - Day" },
        { 117, "Jungle - Area 8 - Day" },
        { 118, "Jungle - Area 7 - Day" },
        { 119, "Jungle - Area 6 - Day" },
        { 120, "Jungle - Area 10 - Day" },
        { 121, "Tower 3 - Base Camp" },
        { 122, "Tower 3 - Area 1" },
        { 123, "Tower 3 - Area 2" },
        { 124, "Tower 3 - Area 10" },
        { 125, "Tower 3 - Area 6" },
        { 126, "Tower 1 - Area 8" },
        { 127, "Tower 3 - Area 7" },
        { 128, "Tower 3 - Area 5" },
        { 129, "Tower 3 - Area 4" },
        { 130, "Tower 3 - Area 3" },
        { 131, "Dundorma Town Square" },
        { 132, "Dundorma Main Area" },
        { 133, "Dundorma Smithy" },
        { 134, "Dundorma Public Tavern" },
        { 135, "Dundorma Arena" },
        { 136, "Dundorma Grand Priest" },
        { 137, "Broken" },
        { 138, "Tower 2" },
        { 139, "Tower 1 - Area 9 (Nest Hole)" },
        { 140, "Desert - Base Camp - Day" },
        { 141, "Desert - Area 2 - Day" },
        { 142, "Desert - Area 7 - Day" },
        { 143, "Desert - Area 3 - Day" },
        { 144, "Desert - Area 6 - Day" },
        { 145, "Desert - Area 5 - Day" },
        { 146, "Desert - Area 1 - Day" },
        { 147, "Desert - Area 4 - Day" },
        { 148, "Desert - Area 8 - Day" },
        { 149, "Desert - Area 9 - Day" },
        { 150, "Desert - Area 10 - Day" },
        { 151, "Swamp - Base Camp - Day" },
        { 152, "Swamp - Area 1 - Day" },
        { 153, "Swamp - Area 2 - Day" },
        { 154, "Swamp - Area 3 - Day" },
        { 155, "Swamp - Area 9 - Day" },
        { 156, "Swamp - Area 8 - Day" },
        { 157, "Swamp - Area 6 - Day" },
        { 158, "Swamp - Area 5 - Day" },
        { 159, "Swamp - Area 7 - Day" },
        { 160, "Swamp - Area 4 - Day" },
        { 161, "Volcano - Base Camp - Day" },
        { 162, "Volcano - Area 4 - Day" },
        { 163, "Volcano - Area 5 - Day" },
        { 164, "Volcano - Area 1 - Day" },
        { 165, "Volcano - Area 2 - Day" },
        { 166, "Volcano - Area 3 - Day" },
        { 167, "Volcano - Area 7 - Day" },
        { 168, "Volcano - Area 6 - Day" },
        { 169, "Volcano - Area 8 - Day" },
        { 170, "Broken" },
        { 171, "Broken" },
        { 172, "Broken" },
        { 173, "My House (Lv1)" },
        { 174, "My House (Lv2)" },
        { 175, "My House (MAX)" },//also house
        { 176, "Dundorma Fort - 03" },
        { 177, "Dundorma Fort - 02" },
        { 178, "Dundorma Fort - 01" },
        { 179, "Dundorma Fort - Base Camp" },
        { 180, "Dundorma Fort - 03" },
        { 181, "Dundorma Fort - 02" },
        { 182, "Dundorma Fort - 01" },
        { 183, "Dundorma Fort - Base Camp" },
        { 184, "Forest and Hills - Base Camp - Night" },
        { 185, "Forest and Hills - Area 6 - Night" },
        { 186, "Forest and Hills - Area 3 - Night" },
        { 187, "Forest and Hills - Area 10 - Night" },
        { 188, "Forest and Hills - Area 8 - Night" },
        { 189, "Forest and Hills - Area 9 - Night" },
        { 190, "Forest and Hills - Area 4 - Night" },
        { 191, "Forest and Hills - Area 2 - Night" },
        { 192, "Forest and Hills - Area 1 - Night" },
        { 193, "Forest and Hills - Area 5 - Night" },
        { 194, "Forest and Hills - Area 7 - Night" },
        { 195, "Forest and Hills - Area 11 - Night" },
        { 196, "Forest and Hills - Area 12 - Night" },
        { 197, "Akantor Battleground" },
        { 198, "Absent" },
        { 199, "Absent" },
        { 200, "Mezeporta" },
        { 201, "Hairdresser" },
        { 202, "Guild Hall Lv1" },
        { 203, "Guild Hall Lv2" },
        { 204, "Guild Hall LvMAX" },
        { 205, "Pugi Farm" },
        { 206, "Old Town Area" },
        { 207, "Old Town Area" },
        { 208, "Absent" },
        { 209, "Absent" },
        { 210, "Private Bar" },
        { 211, "Rasta Bar" },
        { 212, "Jungle Pioneer Secret - 01" },
        { 213, "Jungle Pioneer Secret - 02" },
        { 214, "Desert Pioneer Secret - 01" },
        { 215, "Desert Pioneer Secret - 02" },
        { 216, "Volcano Pioneer Secret - 01" },
        { 217, "Volcano Pioneer Secret - 02" },
        { 218, "Snowy Mountain Pioneer Secret - 01" },
        { 219, "Snowy Mountain Pioneer Secret - 02" },
        { 220, "Volcano - Area 9 - Day" },
        { 221, "Volcano - Area 9 - Night" },
        { 222, "Volcano - Area 10 - Day" },
        { 223, "Volcano - Area 10 - Night" },
        { 224, "Great Forest - Base Camp - Day" },
        { 225, "Great Forest - Base Camp - Night" },
        { 226, "Great Forest - Area 1 - Day" },
        { 227, "Great Forest - Area 1 - Night" },
        { 228, "Great Forest - Area 2 - Day" },
        { 229, "Great Forest - Area 2 - Night" },
        { 230, "Great Forest - Area 3 - Day" },
        { 231, "Great Forest - Area 3 - Night" },
        { 232, "Great Forest - Area 4 - Day" },
        { 233, "Great Forest - Area 4 - Night" },
        { 234, "Great Forest - Area 5 - Day" },
        { 235, "Great Forest - Area 5 - Night" },
        { 236, "Great Forest - Area 6 - Day" },
        { 237, "Great Forest - Area 6 - Night" },
        { 238, "Great Forest - Area 7 - Day" },
        { 239, "Great Forest - Area 7 - Night" },
        { 240, "Great Forest - Area 8 - Day" },
        { 241, "Great Forest - Area 8 - Night" },
        { 242, "Unused Version of the Top of G.Forest (Day)" },
        { 243, "Unused Version of the Top of G.Forest (Night)" },
        { 244, "Code Claiming Room" },
        { 245, "Top of Great Forest - Base Camp - Day" },
        { 246, "Top of Great Forest - Area 1 - Day" },
        { 247, "Highlands - Base Camp - Day" },
        { 248, "Highlands - Base Camp - Night" },
        { 249, "Highlands - Area 1 - Day" },
        { 250, "Highlands - Area 1 - Night" },
        { 251, "Highlands - Area 2 - Day" },
        { 252, "Highlands - Area 2 - Night" },
        { 253, "Highlands - Area 3 - Day" },
        { 254, "Highlands - Area 3 - Night" },
        { 255, "Highlands - Area 4 - Day" },
        { 256, "Caravan Changing Area (Night/Day)" },
        { 257, "Blacksmith" },
        { 258, "Caravan Blimp - Base Camp - Day" },
        { 259, "Caravan Blimp - Base Camp" },//night?
        { 260, "Caravan Area (Raviente \"Great Reward Clause\")" },
        { 261, "Caravan Changing Area" },
        { 262, "Caravan Guest House" },
        { 263, "Caravan Guest House Second Floor" },
        { 264, "Gallery" },
        { 265, "Guuku Farm" },
        { 266, "Absent" },
        { 267, "Absent" },
        { 268, "Absent" },
        { 269, "Absent" },
        { 270, "Absent" },
        { 271, "Absent" },
        { 272, "Interceptor's Base - Base Camp - Day" },
        { 273, "Interceptor's Base - Base Camp - Night" },
        { 274, "Interceptor's Base - Area 1 - Day" },
        { 275, "Interceptor's Base - Area 1 - Night" },
        { 276, "Interceptor's Base - Area 2 - Day" },
        { 277, "Interceptor's Base - Area 2 - Night" },
        { 278, "Interceptor's Base - Area 3 - Day" },
        { 279, "Interceptor's Base - Area 3 - Night" },
        { 280, "Arena with Moat - Base Camp - Day" },
        { 281, "Arena with Moat - Base Camp - Night" },
        { 282, "Cities Map" },
        { 283, "Halk Area" },
        { 284, "Absent" },
        { 285, "Absent" },
        { 286, "PvP Room" },
        { 287, "Absent" },
        { 288, "Gorge - Base Camp - Day" },
        { 289, "Gorge - Base Camp - Night" },
        { 290, "Gorge - Area 1 - Day" },
        { 291, "Gorge - Area 1 - Night" },
        { 292, "Gorge - Area 2 - Day" },
        { 293, "Gorge - Area 2 - Night" },
        { 294, "Gorge - Area 3 - Day" },
        { 295, "Gorge - Area 3 - Night" },
        { 296, "Gorge - Area 4 - Day" },
        { 297, "Gorge - Area 4 - Night" },
        { 298, "Gorge - Area 5 - Day" },
        { 299, "Gorge - Area 5 - Night" },
        { 300, "Gorge - Area 6 - Day" },
        { 301, "Gorge - Area 6 - Night" },
        { 302, "Highlands - Area 4 - Night" },
        { 303, "Highlands - Area 5 - Day" },
        { 304, "Highlands - Area 5 - Night" },
        { 305, "Highlands - Area 6 - Day" },
        { 306, "Highlands - Area 6 - Night" },
        { 307, "Highlands - Area 7 - Day" },
        { 308, "Highlands - Area 7 - Night" },
        { 309, "Solitude Island 9 - Area 3" },
        { 310, "Campaign Tent" }, //in quest?
        { 311, "Raviente Balloon - Day" },
        { 312, "Raviente Balloon - Sunset" },
        { 313, "Raviente Balloon - Night" },
        { 314, "Solitude Island 1 - Area 1" },
        { 315, "Solitude Island 2 - Area 1" },
        { 316, "Solitude Island 3 - Area 1" },
        { 317, "Solitude Island 4 - Area 2" },
        { 318, "Solitude Island 5 - Area 2" },
        { 319, "Solitude Island 6 - Area 2" },
        { 320, "Solitude Island 7 - Area 3" },
        { 321, "Solitude Island 8 - Area 3" },
        { 322, "Tidal Island - Base Camp - Day" },
        { 323, "Tidal Island - Area 1 - Day" },
        { 324, "Tidal Island - Area 2 - Day" },
        { 325, "Tidal Island - Area 3 - Day" },
        { 326, "Tidal Island - Day" },//TODO
        { 327, "Tidal Island - Day" },
        { 328, "Tidal Island - Day" },
        { 329, "Tidal Island - Day" },
        { 330, "Tidal Island - Base Camp - Night" },
        { 331, "Tidal Island - Area 1 - Night" },
        { 332, "Tidal Island - Area 2 - Night" },
        { 333, "Tidal Island - Area 3 - Night" },
        { 334, "Tidal Island - Area 4 - Day" },
        { 335, "Tidal Island - Area 5 - Day" },
        { 336, "Tidal Island - Day" },
        { 337, "Tidal Island (Orange Area 5)" },
        { 338, "Tidal Island - Area 4 - Night" },
        { 339, "Tidal Island - Area 5 - Night" },
        { 340, "SR Room" },
        { 341, "SR Room" },
        { 342, "Large Airship - Base Camp - Day" },
        { 343, "Large Airship Deck - Day" },
        { 344, "Large Airship Crashed" },
        { 345, "Polar Sea - Base Camp - Day" },
        { 346, "Polar Sea - Base Camp - Night" },
        { 347, "Polar Sea - Area 1 - Day" },
        { 348, "Polar Sea - Area 1 - Night" },
        { 349, "Polar Sea - Area 2 - Day" },
        { 350, "Polar Sea - Area 2 - Night" },
        { 351, "Polar Sea - Area 3 - Day" },
        { 352, "Polar Sea - Area 3 - Night" },
        { 353, "Polar Sea - Area 4 - Day" },
        { 354, "Polar Sea - Area 4 - Night" },
        { 355, "Polar Sea - Area 5 - Day" },
        { 356, "Polar Sea - Area 5 - Night" },
        { 357, "Polar Sea - Area 6 - Day" },
        { 358, "Polar Sea - Area 6 - Night" },
        { 359, "World's End - Base Camp" },
        { 360, "World's End - Area 1" },
        { 361, "Flower Field - Base Camp - Day" },
        { 362, "Flower Field - Base Camp - Night" },
        { 363, "Flower Field - Area 1 - Day" },
        { 364, "Flower Field - Area 1 - Night" },
        { 365, "Flower Field - Area 2 - Day" },
        { 366, "Flower Field - Area 2 - Night" },
        { 367, "Flower Field - Area 3 - Day" },
        { 368, "Flower Field - Area 3 - Night" },
        { 369, "Flower Field - Area 4 - Day" },
        { 370, "Flower Field - Area 4 - Night" },
        { 371, "Flower Field - Area 5 - Day" },
        { 372, "Flower Field - Area 5 - Night" },
        { 373, "Top of Tower" },
        { 374, "Deep Crater Area 1" },
        { 375, "Bamboo Entrance - Day" },
        { 376, "Bamboo Entrance - Night" },
        { 377, "Bamboo Forest - Area 1 - Day" },
        { 378, "Bamboo Forest - Area 1 - Night" },
        { 379, "Diva Hall" },
        { 380, "Battlefield Entrance, Deep Crater - Base Camp" },
        { 381, "Absent" },
        { 382, "Absent" },
        { 383, "Absent" },
        { 384, "Absent" },
        { 385, "Absent" },
        { 386, "Absent" },
        { 387, "Absent" },
        { 388, "Absent" },
        { 389, "Absent" },
        { 390, "Tower 01" },
        { 391, "Tower Airship" },
        { 392, "Tower Entrance" },
        { 393, "Tower 02" },
        { 394, "Urgent Tower" },
        { 395, "Absent" },
        { 396, "Battlefield (Varusa)" },
        { 397, "Mezeporta Dupe (nonHD)" },
        { 398, "Duremudira Arena" },
        { 399, "Duremudira Doorway" },
        { 400, "White Lake - Base Camp - Day" },
        { 401, "White Lake - Base Camp - Night" },
        { 402, "White Lake - Area 1 - Day" },
        { 403, "White Lake - Area 1 - Night" },
        { 404, "White Lake - Area 2 - Day" },
        { 405, "White Lake - Area 2 - Night" },
        { 406, "White Lake - Area 3 - Day" },
        { 407, "White Lake - Area 3 - Night" },
        { 408, "White Lake - Area 4 - Day" },
        { 409, "White Lake - Area 4 - Night" },
        { 410, "White Lake - Area 5 - Day" },
        { 411, "White Lake - Area 5 - Night" },
        { 412, "White Lake - Area 6 - Day" },
        { 413, "White Lake - Area 6 - Night" },
        { 414, "Duremudira Door" },
        { 415, "Urgent Tower" },
        { 416, "4th District Tower" },
        { 417, "Berserk Raviente - Base Camp" },
        { 418, "Berserk Raviente Combat Phase 1" },
        { 419, "Berserk Raviente Combat Phase 2" },
        { 420, "Berserk Raviente Combat Phase 3" },
        { 421, "Berserk Raviente Combat Phase 4" },
        { 422, "Berserk Raviente Combat Phase 5" },
        { 423, "Painted Falls - Base Camp - Day" },
        { 424, "Painted Falls - Base Camp - Night" },
        { 425, "Painted Falls - Area 1 - Day" },
        { 426, "Painted Falls - Area 1 - Night" },
        { 427, "Painted Falls - Area 2 - Day" },
        { 428, "Painted Falls - Area 2 - Night" },
        { 429, "Painted Falls - Area 3 - Day" },
        { 430, "Painted Falls - Area 3 - Night" },
        { 431, "Painted Falls - Area 4 - Day" },
        { 432, "Painted Falls - Area 4 - Night" },
        { 433, "Painted Falls - Area 5 - Day" },
        { 434, "Painted Falls - Area 5 - Night" },
        { 435, "Painted Falls - Area 6 - Day" },
        { 436, "Painted Falls - Area 6 - Night" },
        { 437, "Berserk Raviente - Base Camp (Support)" },//TODO: test
        { 438, "Cloud Viewing Fortress - Base Camp" },
        { 439, "Cloud Viewing Fortress - Area 1" },
        { 440, "Berserk Raviente Support Phase 1" },
        { 441, "Berserk Raviente Support Phase 2" },
        { 442, "Berserk Raviente Support Phase 3" },
        { 443, "Berserk Raviente Support Phase 4" },
        { 444, "Berserk Raviente Support Phase 5" },
        { 445, "Guild Hall (Diva Event)" },
        { 446, "Sacred Pinnacle - Base Camp" },
        { 447, "Sacred Pinnacle - Area 1" },
        { 448, "Sanctuary - Base Camp" },//TODO: test
        { 449, "Sanctuary - Area 1" },
        { 450, "Interception/Fortress - Base Camp" },
        { 451, "Interception/Fortress - Base Camp" },
        { 452, "Interception/Fortress - Area 1" },
        { 453, "Interception/Fortress - Area 1" },
        { 454, "Interception/Fortress - Area 2" },
        { 455, "Interception/Fortress - Area 2" },
        { 456, "Interception/Fortress - Area 3 (Main Area)" },
        { 457, "Interception/Fortress - Area 3 (Main Area)" },
        { 458, "Hunter's Road - Area 1" },
        { 459, "Hunter's Road - Base Camp" },
        { 460, "Historical Site - Base Camp" },
        { 461, "Historical Site - Area 1" },
        { 462, "MezFes Entrance" },
        { 463, "Volpkun Together" },
        { 464, "Uruki Pachinko" },
        { 465, "MezFes Minigame" },
        { 466, "Guuku Scoop" },
        { 467, "Nyanrendo" },
        { 468, "Panic Honey" },
        { 469, "Dokkan Battle Cats" },
    });
}
