// Copyright 2023 Doriel Rivalet
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.

namespace EZlion.Mapper;

///<summary>
/// The caravan skill list
///</summary>
public static class SkillCaravan
{
    /// <summary>
    /// Gets the name of the identifier.
    /// </summary>
    /// <value>
    /// The name of the identifier.
    /// </value>
    public static ReadOnlyDictionary<int, string> IDName { get; } = new(new Dictionary<int, string>
    {
        { 0, "None" },
        { 1, "Courage" },
        { 2, "Lander" },
        { 3, "Vine Superhero" },
        { 4, "Mining Expert" },
        { 5, "Insect Expert" },
        { 6, "Vine Master" },
        { 7, "Hot Master" },
        { 8, "Cold Master" },
        { 9, "Bonus Art" },
        { 10, "Combo Tech (Sm)" },
        { 11, "Combo Tech (Med)" },
        { 12, "Combo Tech (Lg)" },
        { 13, "Riser (Sm)" },
        { 14, "Riser (Med)" },
        { 15, "Riser (Lg)" },
        { 16, "Carving Expert" },
        { 17, string.Empty },
        { 18, string.Empty },
        { 19, "Natural Recovery (Sm)" },
        { 20, "Natural Recovery (Med)" },
        { 21, "Natural Recovery (Lg)" },
        { 22, "Master Carver (Sm)" },
        { 23, "Master Carver (Med)" },
        { 24, "Master Carver (Lg)" },
        { 25, "Healing Technique (Sm)" },
        { 26, "Healing Technique (Med)" },
        { 27, "Healing Technique (Lg)" },
        { 28, string.Empty },
        { 29, string.Empty },
        { 30, string.Empty },
        { 31, string.Empty },
        { 32, string.Empty },
        { 33, string.Empty },
        { 34, string.Empty },
        { 36, string.Empty },
        { 37, "Last Minute Ace (Sm)" },
        { 38, "Last Minute Ace (Med)" },
        { 39, "Last Minute Ace (Lg)" },
        { 40, "Goddess of Luck (Sm)" },
        { 41, "Goddess of Luck (Med)" },
        { 42, "Goddess of Luck (Lg)" },
        { 43, string.Empty },
        { 44, string.Empty },
        { 45, string.Empty },
        { 46, string.Empty },
        { 47, string.Empty },
        { 48, string.Empty },
        { 49, string.Empty },
        { 50, string.Empty },
        { 51, string.Empty },
        { 52, string.Empty },
        { 53, string.Empty },
        { 54, string.Empty },
        { 55, string.Empty },
        { 56, string.Empty },
        { 57, string.Empty },
        { 58, string.Empty },
        { 59, string.Empty },
        { 60, string.Empty },
        { 61, string.Empty },
        { 62, string.Empty },
        { 63, string.Empty },
        { 64, string.Empty },
        { 65, string.Empty },
        { 66, string.Empty },
        { 67, string.Empty },
        { 68, string.Empty },
        { 69, string.Empty },
        { 70, string.Empty },
        { 71, string.Empty },
        { 72, string.Empty },
        { 73, string.Empty },
        { 74, string.Empty },
        { 75, string.Empty },
        { 76, "Recovery Items Up" },
        { 77, "Blunt Striker" },
        { 78, "KO Technique" },
        { 79, "Shooting Rampage" },
        { 80, "Art of Dancing" },
        { 81, "Unstable Defender (Sm)" },
        { 82, "Unstable Defender (Med)" },
        { 83, "Unstable Defender (Lg)" },
        { 84, "Rousing Attacker (Sm)" },
        { 85, "Rousing Attacker (Med)" },
        { 86, "Rousing Attacker (Lg)" },
        { 87, "Perfect Defense (Sm)" },
        { 88, "Perfect Defense (Med)" },
        { 89, "Perfect Defense (Lg)" },
        { 90, "Revenge! (Sm)" },
        { 91, "Revenge! (Med)" },
        { 92, "Revenge! (Lg)" },
        { 93, string.Empty },
        { 94, string.Empty },
        { 95, string.Empty },
        { 96, "Combination Celebrity" },
        { 97, string.Empty },
        { 98, "Weapon Art (Sm)" },
        { 99, "Weapon Art (Med)" },
        { 100, "Weapon Art (Lg)" },
        { 101, "Wild Awakening" },
        { 102, "Decisive Hunter" },
        { 103, "Instant Guard Stance" },
        { 104, "Self-Defense" },
        { 105, "Prepared Stance" },
        { 106, "Shield Angel" },
        { 107, "Spear Angel" },
        { 108, "Elite Flame" },
    });
};
