/*
 * © 2023 Doriel Rivalet
 * Use of this source code is governed by a MIT license that can be
 * found in the LICENSE file.
 */

declare module "ezlion" {
  // Define a type for the object structure
  export type FrontierEnumerable = {
    [key: number]: string;
  };

  // TODO this will need to support i18n later on. same for any other strings. prefer numbers or IDs.
  export type FrontierWeaponID =
    | 0
    | 1
    | 2
    | 3
    | 4
    | 5
    | 6
    | 7
    | 8
    | 9
    | 10
    | 11
    | 12
    | 13
    | 14;

  export type FrontierPoogieCostumeName =
    | "First Costume"
    | "Kirin Costume"
    | "Smart Costume"
    | "Cheerful Costume"
    | "Wild Costume"
    | "Hypnoc Costume"
    | "Volganos Costume"
    | "Espinas Costume"
    | "Comrade Costume"
    | "Sporty Costume"
    | "Lively Costume"
    | "Akura Costume"
    | "Azul Costume"
    | "Cool Costume"
    | "Fine Costume"
    | "Beru Costume"
    | "Gospel Costume"
    | "Winning Costume"
    | "Miner Costume"
    | "Paria Costume"
    | "Magisa Costume"
    | "Mischievous Costume"
    | "Gatherer Costume"
    | "Kamu Costume"
    | "Nono Costume"
    | "Tasty Costume"
    | "Fishing Costume"
    | "Legendary Costume"
    | "UNK"
    | "Rainbow Costume"
    | "Hope Costume"
    | "Pokara Costume";

  export type FrontierPoogieGuildOutfitName =
    | "Red & White"
    | "Naked Emperor"
    | "Soporific White"
    | "Black Green Clash"
    | "Silent Suit"
    | "Bewitching Pink"
    | "Nostalgic Stripe"
    | "Soothing Sky"
    | "Gentle Green"
    | "Restless Brown";

  export type FrontierRankBand =
    | ""
    | "Lower"
    | "Lower/Higher"
    | "Higher"
    | "HR5"
    | "Supremacy 1"
    | "Supremacy 2"
    | "G Rank"
    | "Musou 1"
    | "Musou 2"
    | "Twinhead 1"
    | "Twinhead 2"
    | "Zenith★1"
    | "Zenith★2"
    | "Zenith★3"
    | "Zenith★4"
    | "Upper Shiten"
    | "Interception";

  export type FrontierRoadDuremudiraSkillName =
    | "None"
    | ""
    | "Attack"
    | "Defense"
    | "Recovery"
    | "Care"
    | "Pharmacist"
    | "Virus Res."
    | "Guardian Offense"
    | "Guardian Defense"
    | "Frost Res."
    | "Fire Res"
    | "Water Res"
    | "Ice Res"
    | "Thunder Res"
    | "Dragon Res"
    | "Rd P Up"
    | "Revival Sage"
    | "Advancement Guru"
    | "Last Stand"
    | "Bonus Encounter"
    | "All Res"
    | "Rewards Up";

  export type FrontierStyleRankSkillName =
    | ""
    | "Nothing"
    | "Defense+110"
    | "Conquest Def+0"
    | "Conquest Atk+0"
    | "Passive Master"
    | "Soul Revival"
    | "Secret Tech"
    | "Sharpening Up"
    | "Max Sharpen"
    | "Def+60"
    | "Def+100"
    | "Def+110"
    | "Def+120"
    | "Def+130"
    | "Fire Res+15"
    | "Fire Res+20"
    | "Fire Res+22"
    | "Fire Res+24"
    | "Fire Res+25"
    | "Water Res+15"
    | "Water Res+20"
    | "Water Res+22"
    | "Water Res+24"
    | "Water Res+25"
    | "Thunder Res+15"
    | "Thunder Res+20"
    | "Thunder Res+22"
    | "Thunder Res+24"
    | "Thunder Res+25"
    | "Ice Res+15"
    | "Ice Res+20"
    | "Ice Res+22"
    | "Ice Res+24"
    | "Ice Res+25"
    | "Dragon Res+15"
    | "Dragon Res+20"
    | "Dragon Res+22"
    | "Dragon Res+24"
    | "Dragon Res+25"
    | "All Res+7"
    | "All Res+10"
    | "All Res+12"
    | "All Res+14"
    | "All Res+15"
    | "Affinity+20"
    | "Affinity+22"
    | "Affinity+24"
    | "Affinity+26";

  export type FrontierHalkSkillName =
    | ""
    | "None"
    | "Large Monster Priority"
    | "Small Monster Priority"
    | "Near Hunter Priority"
    | "Always Aggressive"
    | "Item Defender"
    | "Rising Intent"
    | "Carving Defender"
    | "Unescapable"
    | "Health Conscious"
    | "Helper [Health]"
    | "Helper [Antidote]"
    | "Helper [Deoderant]"
    | "Gook Luck"
    | "Fast Riser"
    | "Bomber"
    | "Unflinching"
    | "Monster Spotter"
    | "Mapper"
    | "Breath Ball Attack"
    | "Claw Attack Focus"
    | "More Pugi Appearances"
    | "Flying Wyvern Offense"
    | "Fanged Beast Offense"
    | "Piscine Offense"
    | "Carapaceon Offense"
    | "Bird Wyvern Offense"
    | "Elder Dragon Offense"
    | "Elemental Beam Attack"
    | "Demon Drug Dust"
    | "Armour Drug Dust"
    | "Affinity Added"
    | "Improve Status Attack"
    | "Improve Evasion"
    | "Improve Attack"
    | "Signal to Halt Attacks"
    | "Improve Fire Element"
    | "Improve Ice Element"
    | "Improve Water Element"
    | "Improve Thunder Element"
    | "Improve Dragon Element"
    | "Small Bomber"
    | "Supporter"
    | "Elemental Bite"
    | "Brute Wyvern Offense"
    | "Breath Ball Support"
    | "Attack Focus"
    | "Defence Focus"
    | "Jungle Attack"
    | "Desert Attack"
    | "Swamp Attack"
    | "Snowy Mountains Attack"
    | "Volcano Attack"
    | "Tower Attack"
    | "Forest and Hills Attack"
    | "Great Forest Attack"
    | "Arena Attack"
    | "Gorge Attack"
    | "Highlands Attack"
    | "Tidal Island Attack"
    | "Wind Pressure"
    | "Earplugs"
    | "Lone Attack"
    | "Party Attack"
    | "Gathering Affection"
    | "Danger Affection"
    | "Secret Area Affection"
    | "Leviathan Offense"
    | "Rapid Breath Attack"
    | "Empower Attack and Def"
    | "Charging Attack"
    | "Smash Attack"
    | "Polar Sea Attack"
    | "Summer Assault"
    | "Winter Assault"
    | "Contain Monster"
    | "Swift Battle"
    | "Long Battle"
    | "Fanged Wyvern Offense"
    | "Flower Field Attack"
    | "White Lake Attack"
    | "Painted Falls Attack";

  export type FrontierGuildPoogieSkillName =
    | ""
    | "None"
    | "Poogie Thrift"
    | "Poogie Discount"
    | "Poogie Taijutsu"
    | "Poogie Status Attack"
    | "Poogie Reward Technique"
    | "Poogie Defense"
    | "Poogie Escape Technique"
    | "Poogie Transporation"
    | "Poogie Trap Mastery"
    | "Poogie Patience";

  export type FrontierDivaPrayerGemSkillName =
    | ""
    | "None"
    | "Sharpness UP"
    | "Gentle Mounting"
    | "Tail Cutter"
    | "Regeneration UP"
    | "Earth UP"
    | "Heaven UP"
    | "Storm UP"
    | "Cutting UP"
    | "Impact UP"
    | "Shot UP"
    | "Status Duration UP"
    | "Status Weakness UP"
    | "Exploit Weakness UP"
    | "Element UP"
    | "Area Lock"
    | "Shop UP"
    | "Friendship UP"
    | "Blessing UP"
    | "Affinity UP"
    | "Fire Res UP"
    | "Water Res UP"
    | "Ice Res UP"
    | "Dragon Res UP"
    | "Thunder Res UP"
    | "All Res UP";

  export type FrontierCaravanSkillName =
    | ""
    | "None"
    | "Courage"
    | "Lander"
    | "Vine Superhero"
    | "Mining Expert"
    | "Insect Expert"
    | "Vine Master"
    | "Hot Master"
    | "Cold Master"
    | "Bonus Art"
    | "Combo Tech (Sm)"
    | "Combo Tech (Med)"
    | "Combo Tech (Lg)"
    | "Riser (Sm)"
    | "Riser (Med)"
    | "Riser (Lg)"
    | "Carving Expert"
    | "Natural Recovery (Sm)"
    | "Natural Recovery (Med)"
    | "Natural Recovery (Lg)"
    | "Master Carver (Sm)"
    | "Master Carver (Med)"
    | "Master Carver (Lg)"
    | "Healing Technique (Sm)"
    | "Healing Technique (Med)"
    | "Healing Technique (Lg)"
    | "Last Minute Ace (Sm)"
    | "Last Minute Ace (Med)"
    | "Last Minute Ace (Lg)"
    | "Goddess of Luck (Sm)"
    | "Goddess of Luck (Med)"
    | "Goddess of Luck (Lg)"
    | "Recovery Items Up"
    | "Blunt Striker"
    | "KO Technique"
    | "Shooting Rampage"
    | "Art of Dancing"
    | "Unstable Defender (Sm)"
    | "Unstable Defender (Med)"
    | "Unstable Defender (Lg)"
    | "Rousing Attacker (Sm)"
    | "Rousing Attacker (Med)"
    | "Rousing Attacker (Lg)"
    | "Perfect Defense (Sm)"
    | "Perfect Defense (Med)"
    | "Perfect Defense (Lg)"
    | "Revenge! (Sm)"
    | "Revenge! (Med)"
    | "Revenge! (Lg)"
    | "Combination Celebrity"
    | "Weapon Art (Sm)"
    | "Weapon Art (Med)"
    | "Weapon Art (Lg)"
    | "Wild Awakening"
    | "Decisive Hunter"
    | "Instant Guard Stance"
    | "Self-Defense"
    | "Prepared Stance"
    | "Shield Angel"
    | "Spear Angel"
    | "Elite Flame";

  export type FrontierSharpnessColorName =
    | "Red"
    | "Orange"
    | "Yellow"
    | "Green"
    | "Blue"
    | "White"
    | "Purple"
    | "Cyan";

  export type FrontierObjectiveTypeName =
    | "Nothing"
    | "Hunt"
    | "Capture"
    | "Slay"
    | "Damage"
    | "Slay or Damage"
    | "Slay All"
    | "Slay Total"
    | "Deliver"
    | "Break Part"
    | "Deliver Flag"
    | "Esoteric Action";

  export type FrontierQuestToggleMode = "Normal" | "Hardcore" | "Unlimited";

  export type FrontierWeaponStyle =
    | ""
    | "Earth Style"
    | "Heaven Style"
    | "Storm Style"
    | "Extreme Style";

  export type FrontierMonsterName =
    | ""
    | "None"
    | "Rathian"
    | "Fatalis"
    | "Kelbi"
    | "Mosswine"
    | "Bullfango"
    | "Yian Kut-Ku"
    | "Lao-Shan Lung"
    | "Cephadrome"
    | "Felyne"
    | "Veggie Elder"
    | "Rathalos"
    | "Aptonoth"
    | "Genprey"
    | "Diablos"
    | "Khezu"
    | "Velociprey"
    | "Gravios"
    | "Felyne?"
    | "Vespoid"
    | "Gypceros"
    | "Plesioth"
    | "Basarios"
    | "Melynx"
    | "Hornetaur"
    | "Apceros"
    | "Monoblos"
    | "Velocidrome"
    | "Gendrome"
    | "Rocks"
    | "Ioprey"
    | "Iodrome"
    | "Pugis"
    | "Kirin"
    | "Cephalos"
    | "Giaprey / Giadrome"
    | "Crimson Fatalis"
    | "Pink Rathian"
    | "Blue Yian Kut-Ku"
    | "Purple Gypceros"
    | "Yian Garuga"
    | "Silver Rathalos"
    | "Gold Rathian"
    | "Black Diablos"
    | "White Monoblos"
    | "Red Khezu"
    | "Green Plesioth"
    | "Black Gravios"
    | "Daimyo Hermitaur"
    | "Azure Rathalos"
    | "Ashen Lao-Shan Lung"
    | "Blangonga"
    | "Congalala"
    | "Rajang"
    | "Kushala Daora"
    | "Shen Gaoren"
    | "Great Thunderbug"
    | "Shakalaka"
    | "Yama Tsukami"
    | "Chameleos"
    | "Rusted Kushala Daora"
    | "Blango"
    | "Conga"
    | "Remobra"
    | "Lunastra"
    | "Teostra"
    | "Hermitaur"
    | "Shogun Ceanataur"
    | "Bulldrome"
    | "Anteka"
    | "Popo"
    | "White Fatalis"
    | "Yama Tsukami"
    | "Ceanataur"
    | "Hypnocatrice"
    | "Lavasioth"
    | "Tigrex"
    | "Akantor"
    | "Bright Hypnoc"
    | "Red Lavasioth"
    | "Espinas"
    | "Orange Espinas"
    | "Silver Hypnoc"
    | "Akura Vashimu"
    | "Akura Jebia"
    | "Berukyurosu"
    | "Cactus"
    | "Gorge Objects"
    | "Gorge Rocks"
    | "Pariapuria"
    | "White Espinas"
    | "Kamu Orugaron"
    | "Nono Orugaron"
    | "Raviente"
    | "Dyuragaua"
    | "Doragyurosu"
    | "Gurenzeburu"
    | "Burukku"
    | "Erupe"
    | "Rukodiora"
    | "UNKNOWN"
    | "Gogomoa"
    | "Kokomoa"
    | "Taikun Zamuza"
    | "Abiorugu"
    | "Kuarusepusu"
    | "Odibatorasu"
    | "Disufiroa"
    | "Rebidiora"
    | "Anorupatisu"
    | "Hyujikiki"
    | "Midogaron"
    | "Giaorugu"
    | "Mi Ru"
    | "Farunokku"
    | "Pokaradon"
    | "Shantien"
    | "Pokara"
    | "Dummy"
    | "Goruganosu"
    | "Aruganosu"
    | "Baruragaru"
    | "Zerureusu"
    | "Gougarf"
    | "Uruki"
    | "Forokururu"
    | "Meraginasu"
    | "Diorex"
    | "Garuba Daora"
    | "Inagami"
    | "Varusaburosu"
    | "Poborubarumu"
    | "Duremudira"
    | "UNK"
    | "Felyne"
    | "Blue NPC"
    | "UNK"
    | "Cactus"
    | "Veggie Elders"
    | "Gureadomosu"
    | "Harudomerugu"
    | "Toridcless"
    | "Gasurabazura"
    | "Kusubami"
    | "Yama Kurai"
    | "3rd Phase Duremudira"
    | "Zinogre"
    | "Deviljho"
    | "Brachydios"
    | "Berserk Raviente"
    | "Toa Tesukatora"
    | "Barioth"
    | "Uragaan"
    | "Stygian Zinogre"
    | "Guanzorumu"
    | "Starving Deviljho"
    | "UNK"
    | "Egyurasu"
    | "Voljang"
    | "Nargacuga"
    | "Keoaruboru"
    | "Zenaserisu"
    | "Gore Magala"
    | "Blinking Nargacuga"
    | "Shagaru Magala"
    | "Amatsu"
    | "Elzelion"
    | "Arrogant Duremudira"
    | "Rocks"
    | "Seregios"
    | "Bogabadorumu"
    | "Unknown Blue Barrel"
    | "Blitzkrieg Bogabadorumu"
    | "Costumed Uruki"
    | "Sparkling Zerureusu"
    | "PSO2 Rappy"
    | "King Shakalaka";

  export type FrontierWeaponName =
    | "Great Sword"
    | "Long Sword"
    | "Dual Swords"
    | "Sword and Shield"
    | "Hammer"
    | "Hunting Horn"
    | "Lance"
    | "Gunlance"
    | "Heavy Bowgun"
    | "Light Bowgun"
    | "Bow"
    | "Tonfa"
    | "Switch Axe F"
    | "Magnet Spike"
    | "Group";

  export type FrontierWeaponClass = "Blademaster" | "Gunner" | "Both";

  export type FrontierArmorClass = "Either" | "Blademaster" | "Gunner";

  export type FrontierZenithSkill =
    | ""
    | "None"
    | "Skill Slots Up+1"
    | "Skill Slots Up+2"
    | "Skill Slots Up+3"
    | "Skill Slots Up+4"
    | "Skill Slots Up+5"
    | "Skill Slots Up+6"
    | "Skill Slots Up+7"
    | "Flash Conversion Up+1"
    | "Flash Conversion Up+2"
    | "Stylish Assault Up+1"
    | "Stylish Assault Up+2"
    | "Dissolver Up"
    | "Thunder Clad Up+1"
    | "Thunder Clad Up+2"
    | "Ice Age Up"
    | "Hearing Protection Up+1"
    | "Hearing Protection Up+2"
    | "Hearing Protection Up+3"
    | "Wind Res Up+1"
    | "Wind Res Up+2"
    | "Wind Res Up+3"
    | "Wind Res Up+4"
    | "Quake Res Up+1"
    | "Quake Res Up+2"
    | "Poison Res Up+1"
    | "Poison Res Up+2"
    | "Para Res Up+1"
    | "Para Res Up+2"
    | "Sleep Res Up+1"
    | "Sleep Res Up+2"
    | "Vampirism Up"
    | "Drug Knowledge Up"
    | "Assistance Up"
    | "Bullet Saver Up+1"
    | "Bullet Saver Up+2"
    | "Guard Up+1"
    | "Guard Up+2"
    | "Adaptation Up+1"
    | "Adaptation Up+2"
    | "Encourage Up+1"
    | "Encourage Up+2"
    | "Reflect Up+1"
    | "Reflect Up+2"
    | "Reflect Up+3"
    | "Stylish Up"
    | "Vigorous Up"
    | "Obscurity Up"
    | "Soul Up"
    | "Ceaseless Up"
    | "Rush Up";

  export type FrontierSigil =
    | ""
    | "None"
    | "Attack Slayer"
    | "Elemental Slayer"
    | "Status Attack Slayer"
    | "Affinity Slayer"
    | "Defense Slayer"
    | "Stun Value Slayer"
    | "Flying Wyvern Slayer"
    | "Bird Wyvern Slayer"
    | "Carapaceon Slayer"
    | "Piscine Slayer"
    | "Fanged Beast Slayer"
    | "Brute Wyvern Slayer"
    | "Leviathan Slayer"
    | "Elder Dragon Slayer"
    | "Small Monster Slayer"
    | "Elemental Coating/Crystal"
    | "Hot"
    | "Cold"
    | "Morning"
    | "Night"
    | "Breeding Season"
    | "Warm Season"
    | "Cold Season"
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
    | "Sunday"
    | "Manager"
    | "Balloon"
    | "Dowsing"
    | "Hunter Soul"
    | "Soul Collection"
    | "Gook's Friend"
    | "Halk's Friend"
    | "Money Expert"
    | "Exp Expert"
    | "Omnivore"
    | "Carving Division"
    | "Sleeping"
    | "Decoy"
    | "Spoilt"
    | "Unity"
    | "Aid"
    | "Rapid Fire Add"
    | "Ultra Rapid Fire Add"
    | "Disable Rapid"
    | "Heat Cannon Add"
    | "Ballista Saver"
    | "Raw Bow Boost"
    | "Raw SnS Boost"
    | "Sonic Bomb Range"
    | "T.Boost(SnS)"
    | "T.Boost(DS)"
    | "T.Boost(GS)"
    | "T.Boost(LS)"
    | "T.Boost(Lance)"
    | "T.Boost(GL)"
    | "T.Boost(Hammer)"
    | "T.Boost(HH)"
    | "T.Change(SnS)"
    | "T.Change(DS)"
    | "T.Change(GS)"
    | "T.Change(LS)"
    | "T.Change(Lance)"
    | "T.Change(GL)"
    | "T.Change(Ham)"
    | "T.Change(HH)"
    | "T.Change(LBG)"
    | "T.Change(HBG)"
    | "T.Change(Bow)"
    | "Length Up"
    | "Shelling Change"
    | "Note Change 1"
    | "Note Change 2"
    | "Note Change 3"
    | "Arc Shot Change"
    | "Rarity Change"
    | "Shelling Change"
    | "Tech Boost Bow"
    | "Cat Breeder"
    | "Shot Change"
    | "Draw Strength(GS)"
    | "Draw Strength(Hammer)"
    | "Draw Strength(Lance)"
    | "Draw Strength(SnS)"
    | "Draw Strength(DS)"
    | "Draw Strength(LS)"
    | "Draw Strength(HH)"
    | "Draw Strength(GL)"
    | "Draw Strength(Tonfa)"
    | "Tech Boost Tonfa"
    | "Fanged Beast Slayer"
    | "Unsheathed Movement Speed"
    | "Tech Boost Swaxe"
    | "Tech Boost HBG"
    | "Great Sword Up"
    | "Heavy Bowgun Up"
    | "Hammer Up"
    | "Lance Up"
    | "Sword and Shield Up"
    | "Light Bowgun Up"
    | "Dual Swords Up"
    | "Long Sword Up"
    | "Hunting Horn Up"
    | "Gunlance Up"
    | "Bow Up"
    | "Tonfa Up"
    | "Swaxe Up"
    | "Magspike Up"
    | "Zenith Cooldown"
    | "Zenith Duration"
    | "Zenith Fire Res"
    | "Zenith Water Res"
    | "Zenith Ice Res"
    | "Zenith Thunder Res"
    | "Zenith Dragon Res"
    | "Zenith Healing"
    | "Zenith Heroics"
    | "Zenith Attack"
    | "Zenith Elemental"
    | "Zenith Movement Speed"
    | "All Zenith AOEs";
  export type FrontierArmorSkillTree =
    | ""
    | "None"
    | "Health"
    | "Recovery Speed"
    | "Recovery"
    | "Vampirism"
    | "Herbal Science"
    | "Stamina Recovery"
    | "Hunger"
    | "Stamina"
    | "Eating"
    | "Gluttony"
    | "Strong Attack"
    | "Attack"
    | "Lone Wolf"
    | "Issen"
    | "Expert"
    | "Flash Conversion"
    | "Exploit Weakness"
    | "Stylish Assault"
    | "Dissolver"
    | "Status Assault"
    | "Drug Knowledge"
    | "Status"
    | "Abnormality"
    | "Fire Attack"
    | "Water Attack"
    | "Thunder Attack"
    | "Ice Attack"
    | "Dragon Attack"
    | "Elemental Attack"
    | "Bomb Boost"
    | "Gunnery"
    | "Encourage"
    | "Flute Expert"
    | "Martial Arts"
    | "Survivor"
    | "Rage"
    | "Adrenaline"
    | "Skilled"
    | "Trained"
    | "Fasting"
    | "Focus"
    | "Charge Attack Up"
    | "Weapon Handling"
    | "Shiriagari"
    | "Adaptation"
    | "Combat Supremacy"
    | "Vigorous"
    | "Thunder Clad"
    | "Lavish Attack"
    | "Obscurity"
    | "Rush"
    | "Ceaseless"
    | "Point Breakthrough"
    | "Furious"
    | "Determination"
    | "Vitality"
    | "Reflect"
    | "Defense"
    | "Fortication"
    | "Guard"
    | "Auto-Guard"
    | "Breakout"
    | "Sharpening"
    | "Sharpness"
    | "Stylish"
    | "Edgemaster"
    | "Artisan"
    | "Bomb Sword"
    | "Poison Sword"
    | "Paralysis Sword"
    | "Sleep Sword"
    | "Fire Sword"
    | "Water Sword"
    | "Dragon Sword"
    | "Thunder Sword"
    | "Ice Sword"
    | "Fencing"
    | "Sword God"
    | "Steady Hand"
    | "Normal Shot Up"
    | "Pierce Shot Up"
    | "Pellet Shot Up"
    | "Normal Shot Add"
    | "Pierce Shot Add"
    | "Pellet Shot Add"
    | "Crag Shot Add"
    | "Cluster Shot Add"
    | "Poison Coating Add"
    | "Paralysis Coating Add"
    | "Sleep Coating Add"
    | "Mounting"
    | "Gentle Shot"
    | "Loading"
    | "Rapid Fire"
    | "Auto-Reload"
    | "Reload"
    | "Recoil"
    | "Critical Shot"
    | "Precision"
    | "Ammo Combiner"
    | "Bullet Saver"
    | "Sniper"
    | "Spacing"
    | "SnS Tech"
    | "DS Tech"
    | "LS Tech"
    | "GS Tech"
    | "Hammer Tech"
    | "HH Tech"
    | "Lance Tech"
    | "GL Tech"
    | "SAF Tech"
    | "Tonfa Tech"
    | "MS Tech"
    | "HBG Tech"
    | "LBG Tech"
    | "Bow Tech"
    | "All Res Up"
    | "Fire Res"
    | "Water Res"
    | "Thunder Res"
    | "Ice Res"
    | "Dragon Res"
    | "Poison Res"
    | "Paralysis Res"
    | "Sleep Res"
    | "Status Res"
    | "Stun Res"
    | "Deoderant"
    | "Snowball Res"
    | "Vocal Chords"
    | "Def Lock"
    | "Drunk"
    | "Blast Res"
    | "Magnet Res"
    | "Crystal Res"
    | "Freeze Res"
    | "Three Worlds Protection"
    | "Hearing Protection"
    | "Quake Res"
    | "Wind Pressure"
    | "Anti-Theft"
    | "Heat Res"
    | "Cold Res"
    | "Light Tread"
    | "Terrain"
    | "Evasion Boost"
    | "Evasion"
    | "Evade Extender"
    | "Passive"
    | "Protection"
    | "Guts"
    | "Absolute Defense"
    | "Combo Expert"
    | "Everlasting"
    | "Wide-Area"
    | "Whim"
    | "Throwing"
    | "Strong Arm"
    | "Hunger"
    | "Cooking"
    | "Fishing"
    | "Combining"
    | "Alchemy"
    | "Speed Setup"
    | "Íron Arm"
    | "Knife Throwing"
    | "Map"
    | "Psychic"
    | "Stealth"
    | "Incitement"
    | "Backpacking"
    | "Speed Gather"
    | "Gathering"
    | "Carving"
    | "Mindfulness"
    | "Fate"
    | "Pressure"
    | "Monster"
    | "Breeder"
    | "Bond"
    | "Inspiration"
    | "Capture Proficiency"
    | "Relief"
    | "Caring"
    | "Movement Speed"
    | "Reinforcement"
    | "Assistance"
    | "Grace"
    | "Compensation"
    | "Dark Pulse"
    | "Blazing Grace"
    | "Drawing Arts"
    | "Ice Age";
  export type FrontierArmorSkillType =
    | ""
    | "None"
    | "Health and Stamina"
    | "Offensive"
    | "Defensive"
    | "Blademaster"
    | "Gunner"
    | "Hiden"
    | "Resistances"
    | "Status"
    | "Protection"
    | "Items and Combination"
    | "Map and Detection"
    | "Gathering"
    | "Rewards"
    | "Other";
  export type FrontierArmorSkillName =
    | ""
    | "None"
    | "Paralysis Halved"
    | "Negate Paralysis"
    | "Paralysis Doubled"
    | "Sleep Halved"
    | "Negate Sleep"
    | "Sleep Doubled"
    | "Stun Halved"
    | "Negate Stun"
    | "Stun Doubled"
    | "Poison Halved"
    | "Negate Poison"
    | "Double Poison"
    | "Deoderant"
    | "Deoderant2"
    | "Snowball Res"
    | "Snowball Res2"
    | "Sneak"
    | "Taunt"
    | "Health+10"
    | "Health+20"
    | "Health+30"
    | "Health-10"
    | "Health-20"
    | "Health-30"
    | "Recovery Speed+1"
    | "Recovery Speed+2"
    | "Recovery Speed-1"
    | "Recovery Speed-2"
    | "Razor Sharp+1"
    | "Blunt Edge"
    | "Sharpness+1"
    | "Critical Eye+1"
    | "Critical Eye+2"
    | "Critical Eye+3"
    | "Speed Sharpening"
    | "Slothful Sharpening"
    | "Guard+1"
    | "Guard+2"
    | "Guard-1"
    | "Guard-2"
    | "Auto Guard"
    | "Throwing Distance UP"
    | "Reload Speed+1"
    | "Reload Speed+2"
    | "Reload Speed+3"
    | "Reload Speed-1"
    | "Auto Reload"
    | "Recoil Reduction+1"
    | "Recoil Reduction+2"
    | "Normal/Rapid UP"
    | "Pierce/Pierce UP"
    | "Pellet/Spread UP"
    | "Normal S Lv1 Add"
    | "Normal S All Add"
    | "Pierce S Lv1 Add"
    | "Pierce S Lv1&2 Add"
    | "Pierce S All Add"
    | "Pellet S LV1 Add"
    | "Pierce S Lv1&2 Add"
    | "Pellet Shot All Add"
    | "Crag S Lv1 Add"
    | "Crag S Lv1&Lv2 Add"
    | "Crag S All Add"
    | "Cluster S Lv1 Add"
    | "Cluster S Lv1&Lv2 Add"
    | "Cluster S All Add"
    | "Status Attack Up"
    | "Bomber"
    | "Hunger Halved"
    | "Hunger Negated"
    | "Hunger Up Sm"
    | "Hunger Up Lg"
    | "Gourmand"
    | "Scavenger"
    | "Attack Up Small"
    | "Attack Up Medium"
    | "Attack Up Large"
    | "Defense+20"
    | "Defense+30"
    | "Defense+60"
    | "Defense-20"
    | "Defense-30"
    | "Defense-40"
    | "Divine Protection"
    | "Goddess Embrace"
    | "Demonic Protection"
    | "Death Gods Embrace"
    | "Earplugs"
    | "High Grade Earplugs"
    | "Anti-Theft"
    | "Wide Area+1"
    | "Wide Area+2"
    | "Pro Transporter"
    | "All Res UP+5"
    | "All Res UP+10"
    | "All Res UP+20"
    | "All Res-5"
    | "All Res-10"
    | "All Res-20"
    | "Fire Res+10"
    | "Fire Res+20"
    | "Fire Res+30"
    | "Fire Res-10"
    | "Fire Res-20"
    | "Fire Res-30"
    | "Water Res+10"
    | "Water Res+20"
    | "Water Res+30"
    | "Water Res-10"
    | "Water Res-20"
    | "Water Res-30"
    | "Ice Res+10"
    | "Ice Res+20"
    | "Ice Res+30"
    | "Ice Res-10"
    | "Ice Res-20"
    | "Ice Res-30"
    | "Thunder Res+10"
    | "Thunder Res+20"
    | "Thunder Res+30"
    | "Thunder Res-10"
    | "Thunder Res-20"
    | "Thunder Res-30"
    | "Dragon Res+10"
    | "Dragon Res+20"
    | "Dragon Res+30"
    | "Dragon Res-10"
    | "Dragon Res-20"
    | "Dragon Res-30"
    | "Heat Halved"
    | "Heat Cancel"
    | "Heat Cancel2"
    | "Heat Surge Small"
    | "Heat Surge Large"
    | "Cold Halved"
    | "Cold Cancel"
    | "Cold Cancel2"
    | "Cold Surge Small"
    | "Cold Surge Large"
    | "Wind Res Small"
    | "Wind Res Large"
    | "Dragon Wind Breaker"
    | "Map"
    | "Gathering+1"
    | "Gathering+2"
    | "Gathering-1"
    | "Gathering-2"
    | "High Speed Gathering"
    | "Spirits Whim"
    | "Divine Whim"
    | "Spectres Whim"
    | "Devils Whim"
    | "Good Luck"
    | "Great Luck"
    | "Bad Luck"
    | "Horrible Luck"
    | "Fishing Expert"
    | "Detect"
    | "Auto-tracker"
    | "Recovery Items Improved"
    | "Recovery Items Weakened"
    | "Combination+10%"
    | "Combination+15%"
    | "Combination+30%"
    | "Combination-5%"
    | "Combination-15%"
    | "Maximum Bullets"
    | "Alchemy"
    | "Evasion+1"
    | "Evasion+2"
    | "Adrenaline+1"
    | "Adrenaline+2"
    | "Worry"
    | "Item Duration UP"
    | "Item Duration DOWN"
    | "Marathon Runner"
    | "Short Sprinter"
    | "Load UP"
    | "Deviation DOWN"
    | "Deviation UP"
    | "Come on Big Guy"
    | "Speed Eating"
    | "Slow Eating"
    | "Carving Expert"
    | "Hazard Res Small"
    | "Hazard Res Large"
    | "Hazard Prone Small"
    | "Hazard Prone Large"
    | "Quake Res+1"
    | "Vocal Chord Halved"
    | "Vocal Chord Immunity"
    | "BBQ Expert"
    | "BBQ Master"
    | "False BBQ Expert"
    | "Gunnery"
    | "Flute Expert"
    | "Breakout"
    | "Martial Arts"
    | "Strong Arm+1"
    | "Inspiration"
    | "Passive"
    | "Bond"
    | "Guts"
    | "Great Guts"
    | "True Guts"
    | "Pressure Small"
    | "Capture Proficiency"
    | "Poison Coatings Add"
    | "Poison Coating Add"
    | "Sleep Coatings Add"
    | "Fire Attack Small"
    | "Fire Attack Large"
    | "Water Attack Small"
    | "Water Attack Large"
    | "Thunder Attack Small"
    | "Thunder Attack Large"
    | "Ice Attack Small"
    | "Ice Attack Large"
    | "Dragon Attack Small"
    | "Dragon Attack Large"
    | "Starving Wolf+1"
    | "Starving Wolf+2"
    | "Bomb Sword+1"
    | "Bomb Sword+2"
    | "Bomb Sword+3"
    | "Assault Sword+1"
    | "Assault Sword+2"
    | "Assault Sword+3"
    | "Poison Sword+1"
    | "Poison Sword+2"
    | "Poison Sword+3"
    | "Paralysis Sword+1"
    | "Paralysis Sword+2"
    | "Paralysis Sword+3"
    | "Sleep Sword+1"
    | "Sleep Sword+2"
    | "Sleep Sword+3"
    | "Fire Sword+1"
    | "Fire Sword+2"
    | "Fire Sword+3"
    | "Water Sword+1"
    | "Water Sword+2"
    | "Water Sword+3"
    | "Ice Sword+1"
    | "Ice Sword+2"
    | "Ice Sword+3"
    | "Thunder Sword+1"
    | "Thunder Sword+2"
    | "Thunder Sword+3"
    | "Dragon Sword+1"
    | "Dragon Sword+2"
    | "Dragon Sword+3"
    | "Critical Eye+4"
    | "Critical Eye+5"
    | "Attack Up Very Large"
    | "Attack Up Absolute"
    | "Super High-Grade Earplugs"
    | "Peerless"
    | "Precision+2"
    | "Health+40"
    | "Health+50"
    | "Razor Sharp+2"
    | "Defense+90"
    | "Defense+120"
    | "Summer Person"
    | "Winter General"
    | "Artillery Expert"
    | "Artillery God"
    | "Pressure Large"
    | "Capture Guru"
    | "Focus+2"
    | "Focus+1"
    | "Distraction"
    | "SnS Tech 【Sword Saint】"
    | "SnS Tech Kaiden"
    | "SnS Tech Expert"
    | "SnS Tech Novice"
    | "DS Tech 【Dual Dragon】"
    | "DS Tech Kaiden"
    | "DS Tech Expert"
    | "DS Tech Novice"
    | "GS Tech 【Sword King】"
    | "GS Tech Kaiden"
    | "GS Tech Expert"
    | "GS Tech Novice"
    | "LS Tech 【Katana God】"
    | "LS Tech Kaiden"
    | "LS Tech Expert"
    | "LS Tech Novice"
    | "Hammer Tech 【Blunt Beast】"
    | "Hammer Tech Kaiden"
    | "Hammer Tech Expert"
    | "Hammer Tech Novice"
    | "HH Tech 【Flamboyant Emperor】"
    | "HH Tech Kaiden"
    | "HH Tech Expert"
    | "HH Tech Novice"
    | "Lance Tech 【Heavenly Spear】"
    | "Lance Tech Kaiden"
    | "Lance Tech Expert"
    | "Lance Tech Novice"
    | "GL Tech 【Cannon Ruler】"
    | "GL Tech Kaiden"
    | "GL Tech Expert"
    | "GL Tech Novice"
    | "HBG Tech 【Gun Sage】"
    | "HBG Tech Kaiden"
    | "HBG Tech Expert"
    | "HBG Tech Novice"
    | "LBG Tech 【Gun Prodigy】"
    | "LBG Tech Kaiden"
    | "LBG Tech Expert"
    | "LBG Tech Novice"
    | "Bow Tech 【Bow Demon】"
    | "Bow Tech Kaiden"
    | "Bow Tech Expert"
    | "Bow Tech Novice"
    | "Violent Wind Breaker"
    | "Quake Res+2"
    | "Trap Expert"
    | "Trap Master"
    | "Weapon Handling"
    | "Elemental Attack Up"
    | "Elemental Attack Down"
    | "Stamina Rec Large"
    | "Stamina Rec Small"
    | "Stamina Rec Down"
    | "Kickboxing King"
    | "Strong Arm+2"
    | "Throwing Knives+1"
    | "Throwing Knives+2"
    | "Caring+1"
    | "Caring+2"
    | "Caring+3"
    | "Def Lock"
    | "Fencing+1"
    | "Fencing+2"
    | "Status Halved"
    | "Status Immunity"
    | "Status Doubled"
    | "SnS Tech Sword Saint2"
    | "DS Tech Dual Dragon2"
    | "GS Tech Sword King2"
    | "LS Tech Katana God2"
    | "Hammer Tech Blunt Beast2"
    | "HH Tech Flamboyant Emperor2"
    | "Lance Tech Heavenly Spear2"
    | "GL Tech Cannon Emperor2"
    | "HBG Tech Gun Sage2"
    | "LBG Tech Gun Prodigy2"
    | "Bow Tech Bow Demon2"
    | "Passive+1"
    | "Wide Area+3"
    | "Wide Area-1"
    | "Heavy Drinker"
    | "Drunkard"
    | "Crystal Res"
    | "Crystal Vulnerability"
    | "Magnetic Res"
    | "Magnet Vulnerability"
    | "Light Tread"
    | "Relief"
    | "Shiriagari"
    | "Lone Wolf"
    | "Compensation"
    | "Rapid Fire"
    | "Sharpening Artisan"
    | "Unaffected+1"
    | "Unaffected+2"
    | "Unaffected+3"
    | "Reflect+1"
    | "Reflect+2"
    | "Reflect+3"
    | "Honed Blade+1"
    | "Honed Blade+2"
    | "Honed Blade+3"
    | "Strong Attack+1"
    | "Strong Attack+2"
    | "Strong Attack+3"
    | "Strong Attack+4"
    | "Strong Attack+5"
    | "Encourage+1"
    | "Encourage+2"
    | "Grace+1"
    | "Grace+2"
    | "Grace+3"
    | "Vitality+1"
    | "Vitality+2"
    | "Vitality+3"
    | "Vitality-1"
    | "Wrath Awoken"
    | "Buchigire"
    | "Iron Arm+1"
    | "Iron Arm+2"
    | "Breeder"
    | "unk1"
    | "unk2"
    | "Issen+1"
    | "Issen+2"
    | "Issen+3"
    | "Fortify"
    | "Tenacity"
    | "Steady Hand+1"
    | "Mounting+1"
    | "Mounting+2"
    | "Mounting+3"
    | "Exploit Weakness"
    | "Exploit Weakness2"
    | "Reduce Weakness"
    | "Combo Expert+1"
    | "Combo Expert+2"
    | "Combo Expert+3"
    | "Combo Expert-1"
    | "Hunter Life"
    | "Hunter Valhalla"
    | "Critical Shot+1"
    | "Critical Shot+2"
    | "Critical Shot+3"
    | "Evasion+3"
    | "Movement Speed UP+1"
    | "Movement Speed UP+2"
    | "Saving Master"
    | "Saving Expert"
    | "Charge Attack UP+1"
    | "Charge Attack UP+2"
    | "Evade Distance UP"
    | "Red Soul"
    | "Blue Soul"
    | "Vampirism+1"
    | "Vampirism+2"
    | "Adaptation+1"
    | "Adaptation+2"
    | "Dark Finale"
    | "Medical Sage"
    | "Tonfa Tech 【Piercing Phoenix】"
    | "Tonfa Tech Kaiden"
    | "Tonfa Tech Expert"
    | "Tonfa Tech Novice"
    | "Tonfa Tech Large Dragon Club"
    | "Incitement"
    | "Blazing Majesty+1"
    | "Blazing Majesty+2"
    | "Drug Knowledge"
    | "Absolute Defense"
    | "Imperturbable"
    | "Fully Prepared"
    | "Negligence"
    | "Extreme Collection"
    | "Stylish"
    | "Assistance"
    | "Recoil Reduction+3"
    | "Gentle Shot+1"
    | "Gentle Shot+2"
    | "Gentle Shot+3"
    | "Elemental Exploit"
    | "Elemental Diffusion"
    | "Combat Supremacy"
    | "Vigorous"
    | "Vigorous+2"
    | "Status Immunity (Myriad)"
    | "Sword God+1"
    | "Sword God+2"
    | "Thunder Clad"
    | "Status Pursuit"
    | "Drawing Arts+1"
    | "Drawing Arts+2"
    | "Blast Resistance"
    | "Flash Conversion"
    | "Crit Conversion2"
    | "Solid Determination"
    | "Stylish Assault"
    | "Freeze Res"
    | "Ice Age"
    | "Consumption Slayer"
    | "Swaxe Tech 【Edge Marshal】"
    | "Swaxe Tech Kaiden"
    | "Swaxe Tech Expert"
    | "Swaxe Tech Novice"
    | "Swaxe Tech Great Sword General"
    | "Fortification+1"
    | "Fortification+2"
    | "Sniper"
    | "Obscurity"
    | "Evasion Boost"
    | "Rush"
    | "Encourage+2"
    | "Reflect+3"
    | "Skilled"
    | "Ceaseless"
    | "Point Breakthrough"
    | "Abnormality"
    | "Spacing"
    | "Strong Attack+6"
    | "Sword God+3"
    | "Steady Hand+2"
    | "Trained+1"
    | "Trained+2"
    | "Furious"
    | "Magspike Tech 【Magnetic Star】"
    | "Magspike Tech Kaiden"
    | "Magspike Tech Expert"
    | "Magspike Tech Novice"
    | "Magspike Tech Large Magnetic Star";

  export type FrontierArmorColorName =
    | ""
    | "Material Green 0"
    | "Powerful Red 0"
    | "Seized White 0"
    | "Festival Pink 0"
    | "Friendly Blue 0"
    | "Rare Navy 0"
    | "Armored Cyan 0"
    | "Combat Purple 0"
    | "Guided Orange 0"
    | "Gigantic Yellow 0"
    | "Dining Grey 0"
    | "Changing Rainbow"
    | "Material Green 1"
    | "Material Green 2"
    | "Material Green 3"
    | "Material Green 4"
    | "Powerful Red 1"
    | "Powerful Red 2"
    | "Powerful Red 3"
    | "Powerful Red 4"
    | "Festival Pink 1"
    | "Festival Pink 2"
    | "Festival Pink 3"
    | "Festival Pink 4"
    | "Friendly Blue 1"
    | "Friendly Blue 2"
    | "Friendly Blue 3"
    | "Friendly Blue 4"
    | "Rare Navy 1"
    | "Rare Navy 2"
    | "Rare Navy 3"
    | "Rare Navy 4"
    | "Armored Cyan 1"
    | "Armored Cyan 2"
    | "Armored Cyan 3"
    | "Armored Cyan 4"
    | "Combat Purple 1"
    | "Combat Purple 2"
    | "Combat Purple 3"
    | "Combat Purple 4"
    | "Guided Orange 1"
    | "Guided Orange 2"
    | "Guided Orange 3"
    | "Guided Orange 4"
    | "Gigantic Yellow 1"
    | "Gigantic Yellow 2"
    | "Gigantic Yellow 3"
    | "Gigantic Yellow 4"
    | "Dining Grey 1"
    | "Dining Grey 2"
    | "Dining Grey 3"
    | "Dining Grey 4";

  // Define types for each export
  export type ArmorArms = FrontierEnumerable;
  export type ArmorChest = FrontierEnumerable;
  export type ArmorColor = { [key: number]: FrontierArmorColorName };
  export type ArmorHead = FrontierEnumerable;
  export type ArmorLegs = FrontierEnumerable;
  export type ArmorWaist = FrontierEnumerable;
  export type Item = FrontierEnumerable;
  export type Location = FrontierEnumerable;
  export type Monster = { [key: number]: FrontierMonsterName };
  export type ObjectiveType = { [key: number]: FrontierObjectiveTypeName };
  export type PoogieCostume = { [key: number]: FrontierPoogieCostumeName };
  export type Quest = FrontierEnumerable;
  export type RankBand = { [key: number]: FrontierRankBand };
  export type Sharpness = { [key: number]: FrontierSharpnessColorName };
  export type SkillArmor = { [key: number]: FrontierArmorSkillName };
  export type SkillArmorPriority = { [key: number]: FrontierArmorSkillTree };
  export type SkillCaravan = { [key: number]: FrontierCaravanSkillName };
  export type SkillDiva = { [key: number]: FrontierDivaSkillName };
  export type SkillHalk = { [key: number]: FrontierHalkSkillName };
  export type SkillRoadTower = {
    [key: number]: FrontierRoadDuremudiraSkillName;
  };
  export type SkillSigil = { [key: number]: FrontierSigil };
  export type SkillStyleRank = { [key: number]: FrontierStyleRankSkillName };
  export type SkillZenith = { [key: number]: FrontierZenithSkill };
  export type WeaponBlademaster = FrontierEnumerable;
  export type WeaponClass = { [key: number]: FrontierWeaponClass };
  export type WeaponGunner = FrontierEnumerable;
  export type WeaponStyle = { [key: number]: FrontierWeaponStyle };
  export type WeaponType = {
    [key in FrontierWeaponID]: FrontierWeaponName;
  };
  export type PoogieGuildOutfit = {
    [key: number]: FrontierPoogieGuildOutfitName;
  };
  export type QuestToggleMode = { [key: number]: FrontierQuestToggleMode };
  export type SkillDivaPrayerGem = {
    [key: number]: FrontierDivaPrayerGemSkillName;
  };
  export type SkillGuildPoogie = {
    [key: number]: FrontierGuildPoogieSkillName;
  };

  // Export the default object
  const ezlion: {
    ArmorArms: ArmorArms;
    ArmorChest: ArmorChest;
    ArmorColor: ArmorColor;
    ArmorHead: ArmorHead;
    ArmorLegs: ArmorLegs;
    ArmorWaist: ArmorWaist;
    Item: Item;
    Location: Location;
    Monster: Monster;
    ObjectiveType: ObjectiveType;
    PoogieCostume: PoogieCostume;
    Quest: Quest;
    RankBand: RankBand;
    Sharpness: Sharpness;
    SkillArmor: SkillArmor;
    SkillArmorPriority: SkillArmorPriority;
    SkillCaravan: SkillCaravan;
    SkillDiva: SkillDiva;
    SkillHalk: SkillHalk;
    SkillRoadTower: SkillRoadTower;
    SkillSigil: SkillSigil;
    SkillStyleRank: SkillStyleRank;
    SkillZenith: SkillZenith;
    WeaponBlademaster: WeaponBlademaster;
    WeaponClass: WeaponClass;
    WeaponGunner: WeaponGunner;
    WeaponStyle: WeaponStyle;
    WeaponType: WeaponType;
    PoogieGuildOutfit: PoogieGuildOutfit;
    QuestToggleMode: QuestToggleMode;
    SkillDivaPrayerGem: SkillDivaPrayerGem;
    SkillGuildPoogie: SkillGuildPoogie;
  };

  export default ezlion;
}
