name: Actions Status Discord
on: push

jobs:
  actions-status-discord:
    runs-on: ubuntu-latest
    steps:
    - uses: sarisia/actions-status-discord@v1.10.1-pre.0
      if: success()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "`EZlion` Status"
        description: |
          New commit
          Click [here](https://github.com/DorielRivalet/ezlion) to view repository!
        image: ${{ secrets.EMBED_IMAGE }}
        color: 0xff435d
        username: GitHub Actions
        avatar_url: ${{ secrets.AVATAR_URL }}